Spanish by subtle
EventFahrplan/EventFahrplan pull request #330
Opened 2020-10-01 22:23 UTC by 0x5ubt13

# Description
- Completed the Spanish translation in /app/src/main/res/values-es

# Before
- N/A

# After
- N/A

# Contributing guidelines
- Make sure to read the [contributing guidelines](https://github.com/EventFahrplan/EventFahrplan/blob/master/CONTRIBUTING.md) *before* creating this pull request.

Resolves #

2020-10-02 16:01 UTC, johnjohndoe requested changes
Thank you for the Spanish update. I took a first look. There a few things to correct. Please be welcome to rewrite/modify your existing commits and `git push --force` your `spanish_by_subtle` branch to update this pull request. If you need help let me know.

2020-10-10 20:12 UTC, johnjohndoe commented
@0x5ubt13 Please let me know if I can help with the pull request - but take your time if you are busy these days.

2020-10-21 15:29 UTC, johnjohndoe commented
@0x5ubt13 If you do not have time to finish this, please let me know so I can offer the issue to somebody else.

2020-10-21 15:36 UTC, 0x5ubt13 commented
Oh I forgot about this project completely, I'm so sorry about it. I'll take a look at the corrections tonight and get it done

2020-10-21 23:49 UTC, 0x5ubt13 reviewed
I've reviewed all the comments and applied the necessary changes as per their request.

2020-10-21 23:50 UTC, 0x5ubt13 commented
All changes to the pull request should make the whole lot hopefully meet your criteria :)

2020-10-22 14:08 UTC, johnjohndoe commented on app/src/main/res/values-es/strings.xml
> +    <string name="validation_error_url_without_query">"         <xliff:g example="Engelsystem" id="urlType">%s</xliff:g> URL sin query.     "</string>
This was not fixed. I took care of it.

2020-10-22 14:09 UTC, johnjohndoe commented on app/src/main/res/values-es/strings.xml
> +    <string name="preference_summary_engelsystem_json_export_url">"         <![CDATA[Para ver tus turnos por favor pon tu URL <u>personal</u> aquí.<br/><br/>         1. Haz login en tu cuenta Engelsy
You did not move the string to another file. I did that now.

2020-10-22 14:14 UTC, johnjohndoe approved these changes
Thank you @0x5ubt13 for the "late night" update ;-)

I had to fix a few left-overs (I already commented those). Also, you deleted the `session_duration` string which I brought back. Finally, I squashed your commits into a single commit. As a side note for future commits: please avoid merging `master` into your branch. Instead you can rebase your branch.

Now, the translation looks fine. I checked in on a Pixel 2, Android 10. Thank you once again for your time!

2020-10-22 14:15 UTC, merged

2024-01-19 21:03 UTC, johnjohndoe commented
Happy new year @0x5ubt13! I started managing translations for the EventFahrplan at [Crowdin](https://crowdin.com/project/eventfahrplan). I like to invite you to join there if you like.