French translation update
EventFahrplan/EventFahrplan pull request #333
Opened 2020-10-03 21:47 UTC by Omicron666

# Description
French translation of missing strings
+fix escaped tags
+rewording

Resolves https://github.com/EventFahrplan/EventFahrplan/issues/170

2020-10-04 11:04 UTC, johnjohndoe requested changes
Thank you for working on the French translation. I executed a first review and pointed out a few issues to change.

Once you are done with your changes, feel free to reorganize the commits on your `french-translation` branch using commands like `git commit --amend` or `git rebase --interactive` and to update this pull request via `git push --force`.

In any case let me know if I can help.

2020-10-10 20:13 UTC, johnjohndoe commented
@Omicron666 Please let me know if I can help with the pull request - but take your time if you are busy these days.

2020-10-21 15:29 UTC, johnjohndoe commented
@Omicron666 If you do not have time to finish this, please let me know so I can offer the issue to somebody else.

2020-10-23 21:21 UTC, Omicron666 commented
> @Omicron666 If you do not have time to finish this, please let me know so I can offer the issue to somebody else.

@johnjohndoe yes, please do. not on it at the moment

2020-11-17 19:25 UTC, johnjohndoe commented
@Omicron666 Happy November. :maple_leaf: If you happen to have time to pick up this pull request again I am very glad to assist you to get it finalized. No time pressure here!

2020-11-22 17:11 UTC, Omicron666 commented
> 
> 
> @Omicron666 Happy November. 🍁 If you happen to have time to pick up this pull request again then I will be very glad to assist you to get it finalized. No time pressure here!

on it now

2020-11-22 17:41 UTC, Omicron666 commented on app/src/main/res/values-fr/strings.xml
> +    <string name="progress_loading_data">Récupération du programme  &#8230;</string>
fixed for progress_processing_data too

2020-11-22 19:07 UTC, johnjohndoe approved these changes
Merci for taking time again and the latest changes! Looks good to me.

:heavy_check_mark: Successfully tested on Pixel 2, Android 10.

2020-11-22 19:08 UTC, merged

2024-01-19 21:05 UTC, johnjohndoe commented
Happy new year @omicron321! I started managing translations for the EventFahrplan project at [Crowdin](https://crowdin.com/project/eventfahrplan). I like to invite you to join there if you like.