Optimize Room View Update
EventFahrplan/EventFahrplan pull request #482
Opened 2022-05-08 08:04 UTC by NWuensche

Fixes #458

2022-05-08 19:03 UTC, johnjohndoe requested changes
Awesome :heart_eyes_cat: I appreciate that you spent your time and thoughts in working on this nasty issue. I had a quick look through the code and just found a few minor and cosmetic issues for you. I will test run the app once you are done. Please also document in the pull request which devices/Android versions and build flavors you tested with. Just copy the format I used in other PRs.

2022-05-08 19:40 UTC, johnjohndoe commented on app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/RoomColumnViewCache.kt
> +    private fun createFilledRecyclerView(
The function name seems outdated. Here the view is created - but the data is added in `updateData()`.

2022-05-09 16:07 UTC, NWuensche commented on app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/FahrplanFragment.kt
> +    private val roomUICache: IRoomColumnViewCache by lazy { RoomColumnViewCache(this) }
Seems like a good idea to hide the concrete details. I will implement it like that :)

2022-05-09 16:26 UTC, NWuensche commented on app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/RoomColumnViewCache.kt
> +                adapter.notifyDataSetChanged() //e.g. favour article
wrong app ^^

2022-05-09 16:34 UTC, NWuensche commented
I think I fixed everything :)

2022-05-10 18:34 UTC, johnjohndoe requested changes
Thank you for the latest changes. A little follow-up here. 

---

Please also clean-up you branch to only include the final commits to be merged. Rebasing and force-pushing is fine. It's still your branch :muscle: No need to merge `master` into your branch, see [contribution guide](https://github.com/EventFahrplan/EventFahrplan/blob/master/CONTRIBUTING.md).

2022-05-10 18:34 UTC, johnjohndoe commented on app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/roomcolumnviews/RoomColumnViewCache.kt
> +internal interface IRoomColumnViewCache {
Do we need the additional layer of indirection introduced by `RoomColumnViewProvider`?  I thought we could just rename `IRoomColumnViewCache` to `RoomColumnViewProvider` and drop `RoomColumnViewProvider` itself.

BTW: No personal preference - just for consistency: the `I` prefix isn't used in this project. I would therefore prefer the suggested naming.

2025-04-20 20:35 UTC, johnjohndoe commented
@NWuensche Meanwhile, I migrated the session cards from XML-based layout to Compose UI, see https://github.com/EventFahrplan/EventFahrplan/pull/734. Do you want to pick up your work again based on the latest implementation? If not, I would be fine if you close this pull request. In any case, can you please update issue https://github.com/EventFahrplan/EventFahrplan/issues/458 with the current behavior?

2025-04-21 16:44 UTC, NWuensche commented
Sure, I will look into it. :) However, can you please first fix the Merge Conflicts before I look into it and give me a short notification afterwards please?

2025-04-21 16:46 UTC, NWuensche commented
Sorry, my bad, I read the comment wrong, my bad :D 

Yes, I will try if the error is easier to solve now that we use Compose there. I hope I can find the time to get back into it next week, this week I'm already quite busy.

2025-04-21 17:32 UTC, johnjohndoe commented
Take your time. You can reuse the branch and force push a new fix. I am looking forward to your analysis.

2025-05-04 19:06 UTC, NWuensche commented
@johnjohndoe

So I've fiddled around with it and it is quite hard to adapt the idea
from before to ComposeViews. Before, I could just update the data
inside the Adapter of the RecyclerView. However, I'm a bit lost on how
to do that for ComposeViews. Storing a separate VM for every ComposeView and updating the StateFlow inside it seems
a bit weird, but I don't have any better idea. Do you think this is
the way to go?

Am Mo, 21. Apr 10:32, schrieb GitHub Notifications:
>johnjohndoe left a comment (EventFahrplan/EventFahrplan#482)
>
>Take your time. You can reuse the branch and force push a new fix. I am looking forward to your analysis.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/EventFahrplan/EventFahrplan/pull/482#issuecomment-2819085416
>You are receiving this because you were assigned.
>
>Message ID: ***@***.***>

2025-05-04 20:13 UTC, johnjohndoe commented
Did you check the current implementation with a **release build**? Compose UI performs much slower in **debug builds**.

If the freezing as described in #458 is still present I recommend to digg for the source of the problem, e.g. measuring the actual time in each app layer (database query, app repository, view model transformation, view model emission, fragment/compose rendering). This will hopefully give us an educated guess where the bottleneck comes from.

Resources:
- [How to Use Kotlin's Timing API](https://www.youtube.com/watch?v=VRxp3DD-ULQ)
- [Optimize Your Kotlin App for Faster Performance - Learn How to Measure Execution Time](https://www.youtube.com/watch?v=T8G4KXKl6bU)

2025-05-05 17:49 UTC, NWuensche commented
I've tried the release version, but it still feels slow with the 38c3
data. Everytime I click on something, it freezes the whole UI for have
a second. Also when I open an event and go back to the event list, the
whole UI freezes for one second.

I already did the digging before. The issue is/was that everytime some
data changes, *all* event list views get completely recalculated and redrawn. 
The solution was to keep the views and only update the data. This
helped with the recycler views, but now with the Compose Views it's a
bit more involved.

2025-05-05 18:47 UTC, johnjohndoe commented
Other things which I noticed but haven't had time to look into are that **network requests** (see debug output) are running probably too often and that **database reads** are potentially happening more than needed (see logs from observable `AppRepository`). - These might cause unnecessary UI rendering which keeps the main thread busy.

2025-05-14 21:35 UTC, johnjohndoe commented
This article might also be interesting in the context of this issue:

- [Stale Data & Leaks were killing my Kotlin apps for 5 years. Here’s the fix.](https://proandroiddev.com/how-to-load-data-kotlin-898f9add9c6f)

2025-06-06 18:25 UTC, NWuensche commented
@johnjohndoe I think I've found a way easier solution that works for me as well :) Can you please have a look and double-check that I've didn't introduced a bug?

2025-06-06 18:57 UTC, johnjohndoe requested changes
Looks reasonable. I still need to test it. Can you please update your commit message and squash the commits?

2025-06-06 18:57 UTC, johnjohndoe commented on app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/FahrplanFragment.kt
> +    val roomDataCache: MutableMap<String, RoomData> = mutableMapOf()
Can the property be private?

2025-06-06 18:57 UTC, johnjohndoe commented on app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/FahrplanFragment.kt
> +                columnsLayout.removeViewAt(roomIndex)
Why do we need to remove the index? When does this actually happen?

2025-06-06 22:51 UTC, johnjohndoe commented on app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/FahrplanFragment.kt
> +            roomDataCache[roomData.roomName] = roomData
We also parse the `guid` or a `room` from the XML. It is available as `roomIdentifier` in the `Session` model. `SessionsTransformer` does not pass it through into `RoomData` but we could add it.

2025-06-06 22:51 UTC, johnjohndoe commented on app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/FahrplanFragment.kt
> +    val roomDataCache: MutableMap<String, RoomData> = mutableMapOf()
Please move the property up to the top of the class like other properties.

2025-06-06 22:54 UTC, johnjohndoe commented on app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/FahrplanFragment.kt
> +    val roomDataCache: MutableMap<String, RoomData> = mutableMapOf()
Naming suggestion (like other maps are named in the project): `renderedRoomDataByRoomName`

2025-06-06 23:14 UTC, johnjohndoe commented
WOW! I tested it on a device. I can notice a huge difference. This is awesome. Let's clean up the branch and get this merged. Thank you for the investigation!! :+1:

2025-06-07 19:10 UTC, NWuensche commented on app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/FahrplanFragment.kt
> +    val roomDataCache: MutableMap<String, RoomData> = mutableMapOf()
Done

2025-06-07 19:22 UTC, NWuensche commented on app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/FahrplanFragment.kt
> +                columnsLayout.removeViewAt(roomIndex)
We don't call `removeAllViews()` at the beginning anymore, hence, everytime the `columnsLayout` is updated (for example, after favoring an event), we have to remove the "old" views, otherwise these would be there twice I guess.

2025-06-07 19:34 UTC, NWuensche commented
@johnjohndoe Fixed everything and I hope that I've answered your remaining question :)

2025-06-08 08:05 UTC, johnjohndoe commented on app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/FahrplanFragment.kt
> +    private val renderedRoomGuidHashByRoomName: MutableMap<String, Int> = mutableMapOf()
With the current implementation the property should be named: `renderedRoomDataHashCodeByRoomGuid`.

2025-06-08 08:06 UTC, johnjohndoe commented
> @johnjohndoe Fixed everything and I hope that I've answered your remaining question :)

Did you see that tests fail now. You need to adapt `SessionsTransformer` to be able to add the `roomIdentifier` to `RoomData`.

2025-06-08 08:08 UTC, johnjohndoe commented on app/src/main/java/nerd/tuxmobil/fahrplan/congress/models/RoomData.kt
> +        val roomGuid: String,
Please use the term `roomIdentifier` in the app layer. By this name I want to keep the property neutral/separated from whatever is assigned in the network and database layer. There the term `roomGuid` is used.

2025-06-08 08:12 UTC, johnjohndoe commented on app/src/main/java/nerd/tuxmobil/fahrplan/congress/repositories/SessionsTransformer.kt
> +                    roomGuid = sessions.first().roomIdentifier,
Are you sure the `first` session has the correct `roomIdentifier` for each session? Would be good to have a unit test which covers this.

2025-06-09 08:50 UTC, NWuensche commented on app/src/main/java/nerd/tuxmobil/fahrplan/congress/repositories/SessionsTransformer.kt
> +                    roomGuid = sessions.first().roomIdentifier,
I've added a unit test now. However, I don't really see how a unit test will help here, doesn't this depend on the actual data? I could use the roomName in case the roomIdentifier is empty, do you think this would be helpful?

2025-06-09 09:25 UTC, NWuensche commented
I've also fixed the tests. However, there are still two tests that also fail on master, so I guess I shouldn't fix them inside this PR, right?

2025-06-09 11:25 UTC, johnjohndoe commented on app/src/main/java/nerd/tuxmobil/fahrplan/congress/repositories/SessionsTransformer.kt
> +                    roomGuid = sessions.first().roomIdentifier,
That's true. The test would only reflect the desired behavior. 

A missing room identifier is indeed a problem. The feature is also relatively new. Maybe, the room name makes more sense. Not sure.

2025-06-09 11:28 UTC, johnjohndoe commented
Interesting. Seems like they depend on the locale. Please file an issue and ignore them here.

2025-06-09 18:00 UTC, NWuensche commented on app/src/main/java/nerd/tuxmobil/fahrplan/congress/repositories/SessionsTransformer.kt
> +                    roomGuid = sessions.first().roomIdentifier,
Then we'll stick with the roomName. I guess it's better when it is more common. I guess it will also be unique enough :D

2025-06-09 18:01 UTC, NWuensche commented
@johnjohndoe I'm done again, can you check again. I will also try to fix the two tests in another PR

Edit: Created a issue under https://github.com/EventFahrplan/EventFahrplan/issues/757
 and fixed in https://github.com/EventFahrplan/EventFahrplan/pull/758

2025-06-09 20:28 UTC, johnjohndoe commented
Thank you for the update.

The commit message currently only states what can be read from the code change: `Add cache for rendered rooms `.
Please state in the summary line why you add the cache and which user-facing issue is addressed in the details of the commit. I like to encapsulate all related information in the commit message so GitHub or any other hosting platform will not be needed to understand the commit in the future.

2025-06-09 20:29 UTC, johnjohndoe commented on app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/FahrplanFragment.kt
> +     * Used to redraw only the rooms that really changed
`that really changed` could be more verbose like `that visually change because a session is favored` or something like that

2025-06-09 20:30 UTC, johnjohndoe commented on app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/FahrplanFragment.kt
> +    private val renderedRoomHashByRoomName: MutableMap<String, Int> = mutableMapOf()
Concise: `private val renderedRoomHashByRoomName = mutableMapOf<String, Int>()

2025-06-09 20:30 UTC, johnjohndoe commented on app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/FahrplanFragment.kt
> +            if (renderedRoomHashByRoomName[roomData.roomName] == roomData.hashCode()) continue //Only redraw rooms that changed
The comment is redundant, I would say because the cache is commented above.

2025-06-09 20:32 UTC, johnjohndoe commented on app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/FahrplanFragment.kt
> +                columnsLayout.removeViewAt(roomIndex)
But why the `if` check and not a "replace value at index"?

2025-06-10 16:52 UTC, NWuensche commented on app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/FahrplanFragment.kt
> +                columnsLayout.removeViewAt(roomIndex)
AFAIK, there is no replace-function, only remove+add. If I've missed something you know of, please tell me :)

2025-06-11 17:24 UTC, johnjohndoe commented on app/src/main/java/nerd/tuxmobil/fahrplan/congress/schedule/FahrplanFragment.kt
> +                columnsLayout.removeViewAt(roomIndex)
My bad. I also cannot find such as function.

But why is the `columnsLayout.size > roomIndex` check needed?

2025-06-12 18:52 UTC, NWuensche commented
Because in the first iteration (when the cache is empty), there's
nothing to remove. If you try to remove a view there, then it would
throw an exception.


Am Mi, 11. Jun 10:25, schrieb GitHub Notifications:
>@johnjohndoe commented on this pull request.
>
>
>
>> @@ -430,7 +439,12 @@ class FahrplanFragment : Fragment(), MenuProvider {
>                     )
>                 }
>             }
>-            columnsLayout.addView(roomColumnView)
>+
>+            if (columnsLayout.size > roomIndex) {
>+                columnsLayout.removeViewAt(roomIndex)
>
>My bad. I also cannot find such as function.
>
>But why is the `columnsLayout.size > roomIndex` check needed?
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/EventFahrplan/EventFahrplan/pull/482#discussion_r2140718833
>You are receiving this because you were assigned.
>
>Message ID: ***@***.***>

2025-06-12 21:52 UTC, merged

2025-06-12 21:56 UTC, johnjohndoe commented
:bulb: By the way, the caching probably works now because the `Session` class has been migrated to become a `data class` with `hasAlarms` and `isHighlighted` being included in `equals` and `hashCode` functions. See #631.