Transpile 'DateInfos.java' Class
EventFahrplan/EventFahrplan pull request #509
Opened 2022-09-09 20:31 UTC by isiko

# Description
The `DateInfos` still uses Java. As the standard language for Android apps is now Kotlin, I transpiled them to Kotlin. I used the transpiling tool, provided by Android Studio and made some cleanups afterwards.

# Tested on (with all build flavors):
- Phone (Pixel 2), API lvl 24 Emulator
- Phone (Pixel 2), API lvl 33 Emulator

Relates to #448

2022-09-10 07:33 UTC, johnjohndoe requested changes
Thank you for the conversion. Here are a few improvement suggestions.

2022-09-10 07:33 UTC, johnjohndoe commented on app/src/main/java/nerd/tuxmobil/fahrplan/congress/models/DateInfos.kt
> +        } != null
I believe `any()` can be used here: `return any { (dayIndex, date) -> dayIndex == sessionListDay && date == currentDate }`. Please verify.

2022-09-10 07:33 UTC, johnjohndoe commented on app/src/main/java/nerd/tuxmobil/fahrplan/congress/models/DateInfos.kt
> +    fun sameDay(timestamp: Moment, sessionListDay: Int): Boolean {
An empty line please.

2022-09-10 07:33 UTC, johnjohndoe commented on app/src/main/java/nerd/tuxmobil/fahrplan/congress/models/DateInfos.kt
> +     */
KDoc: Please merge like this `Returns the index of today if found, [DateInfo.DAY_INDEX_NOT_FOUND] otherwise.`

2022-09-10 07:33 UTC, johnjohndoe commented on app/src/main/java/nerd/tuxmobil/fahrplan/congress/models/DateInfos.kt
> +            this.forEach { dateInfo ->
`this` is redudant.

2022-09-10 07:33 UTC, johnjohndoe commented on app/src/main/java/nerd/tuxmobil/fahrplan/congress/models/DateInfos.kt
> +    companion object {
Can be `private`.

2022-09-10 07:33 UTC, johnjohndoe commented on app/src/main/java/nerd/tuxmobil/fahrplan/congress/models/DateInfos.kt
> +import info.metadude.android.eventfahrplan.commons.temporal.Moment.Companion.now
No imports for `Moment` companion function please.

2022-09-11 16:12 UTC, johnjohndoe submitted a review, later dismissed
Thank you :+1: Ready to be merged.

2022-09-11 16:14 UTC, isiko commented
Sorry for pushing, didn't see your push :grimacing:

2022-09-11 16:27 UTC, merged